### ISSUE TITLE
commercialization?

### ISSUE THREAD

**Issue by isitgto** [Fossana/discounted-cfr-poker-solver#2]
Hi would you be interested in developing this for a commercial solver?

**Comment by Fossana** [comment]
Potentially.

> 
> 
> Hi would you be interested in developing this for a commercial solver?

**Comment by Fossana** [comment]
> 
> 
> Hi would you be interested in developing this for a commercial solver?

Potentially. I'm working on a c++ version that is so far 3x faster than the code I posted here.

**Comment by isitgto** [comment]
Thanks for responding. Would you mind emailing me when you have a moment please? isitgto@gmail.com.
